name: chitchat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^1.6.3
  firebase_auth: ^4.13.0
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.5
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.1.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.6
  http: 0.13.3
  image_picker: ^1.0.4
  story_view: 0.16.3

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "icon"
  ios: true
  image_path: "img/Logo dark.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - img/google.png
    - img/logo12.png
    - img/camera.png
    - img/gallery.png
    - img/are.png
    - img/benaya.png
    - img/hans.png
    - img/jesen.png
    - img/roy.png
    - img/anto.png
    - img/Logo dark.png
    - img/note.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
    - family: Noto Serif
      fonts:
        - asset: fonts/Noto_Serif/NotoSerif-VariableFont_wdth,wght.ttf
        - asset: fonts/Noto_Serif/NotoSerif-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-VariableFont_wght.ttf
        - asset: fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
          style: italic
    - family: Recursive
      fonts:
        - asset: fonts/Recursive/Recursive-VariableFont_CASL,CRSV,MONO,slnt,wght.ttf
